### ISSUE TITLE
Support for Typed POJO

### ISSUE THREAD

**Issue by mtraynham** [Pozo/mapstruct-kotlin#10]
I have an object that is generically typed, for example:

```kotlin
import com.github.pozo.KotlinBuilder

interface Bar

@KotlinBuilder
data class Foo<T : Bar>(
   val bar: T
)
```

When I build this, it generates the following:

```java
public final class FooBuilder {
  private T bar;

  public FooBuilder setBar(T bar) {
    this.bar = bar;
    return this;
  }

  public Foo create() {
    return new Foo(bar);
  }

  public static FooBuilder builder() {
    return new FooBuilder();
  }
}
```

But it also dumps the following error:
```
  private T bar;
          ^
  symbol:   class T
  location: class FooBuilder/.../FooBuilder.java:6: error: cannot find symbol
  public FooBuilder setBar(T bar) {
                           ^
  symbol:   class T
  location: class FooBuilder
```

This seems very close and is simply missing the same type restriction on the Builder class.

**Comment by Pozo** [comment]
Thank you for your report. I think I found a solution for this issue, you can look over it in the linked pull request.

**Comment by Pozo** [comment]
@mtraynham Now it's available from the central repository, the version number is [1.3.1.2](https://search.maven.org/artifact/com.github.pozo/mapstruct-kotlin-processor/1.3.1.2/jar)
