### ISSUE TITLE
Missing imports for nested DTOs

### ISSUE THREAD

**Issue by driver733** [Pozo/mapstruct-kotlin#11]
Given:

```
@KotlinBuilder
data class A(var b: B?) {
    data class B(var name: String)
}

```

Expected:

```
public final class ContactInfoBuilder {
  public static CallbackApplication.ContactInfo builder() {
    return new CallbackApplication.ContactInfo();
  }
}
```

Actual:

```
public final class ContactInfoBuilder {
  public static ContactInfo builder() {
    return new ContactInfo();
  }
}
```

Useful links:
https://stackoverflow.com/questions/34271401/how-to-generate-inner-class-in-javapoet-in-java

https://github.com/square/javapoet/blob/master/src/test/java/com/squareup/javapoet/TypeSpecTest.java#L645

**Comment by Pozo** [comment]
@driver733 Now it's available from the central repository, the version number is [1.3.1.2](https://search.maven.org/artifact/com.github.pozo/mapstruct-kotlin-processor/1.3.1.2/jar)
