### ISSUE TITLE
Add support for Gradle incremental annotation processing

### ISSUE THREAD

**Issue by mtraynham** [Pozo/mapstruct-kotlin#18]
Add support for Gradle's incremental annotation processing with Kapt should help speed up build times.  MapStruct is planning on this for 1.4.0, https://github.com/mapstruct/mapstruct/pull/1971.

Currently kotlin users need to disable it with 
```
kapt.incremental.apt=false
```

Theoretically, you'll likely just need to add a META-INF/services file that suggests that annotation processor is incremental.

_src/main/resources/META-INF/gradle/incremental.annotation.processors_ 
```
com.github.pozo.BuilderProcessor,isolating
```
https://docs.gradle.org/6.3/userguide/java_plugin.html#making_an_annotation_processor_incremental

**Comment by RomanMinenok** [comment]
Well, this a blocker for me currently to use it in my project

**Comment by Pozo** [comment]
@mtraynham Thank you for your contribution! 🎊 

@RomanMinenok @mtraynham The release was successful, [it will be available soon](https://search.maven.org/artifact/com.github.pozo/mapstruct-kotlin) the version number will be `1.4.0.0`.

**Comment by RomanMinenok** [comment]
@Pozo awesome, thank you for the heads-up!
