### ISSUE TITLE
JPA entity class issue

### ISSUE THREAD

**Issue by silver0r** [Pozo/mapstruct-kotlin#19]
Hi
I think this project is very useful.
I have question.

How can I solve this if we write JPA entity as class (not data class)?
@KotlinBuilder annotation is only available in data class.

TYSM

**Comment by silver0r** [comment]
You know that primary constructor issue about kotlin-jpa, no-arg gradle plugin make constructor when build complete (byte code).

It's not work
```
@Entity
class Member(
    @Id
    @GeneratedValue
    var id: Long

    @Column(length = 100)
    var name: String
)

```

It's working
```
@Entity
class Member {
    @Id
    @GeneratedValue
    var id: Long = 0L

    @Column(length = 100)
    var name: String = ""
}
```

**Comment by Pozo** [comment]
@silver0r Thank you for your report, however this library intention is only hanging on Kotlin's data classes and mapstruct.

If you would like to do something you mentioned above, you should use mapstruct only.
