### ISSUE TITLE
Does not fail if applied to non-data-class, and MapStruct just fails to create the mapper

### ISSUE THREAD

**Issue by arberg** [Pozo/mapstruct-kotlin#8]
Hi, 

A MapStruct/mapstruct-kotlin issue: 

When I forget to create my class as data class, but apply @KotlinBuilder then neither KotlinBuilder nor MapStruct produce an error during build, but MapStruct does not build the mapper. It just fails silently to do anything. This made it difficult to track down such issues. 

If possible and easy, it would be really nice if @KotlinBuilder just fails if annotation is applied to non-data-class. Without @KotlinBuilder, MapStruct gives fine error about missing constructor.

Best Alex

Versions
    api 'org.mapstruct:mapstruct:1.3.1.Final'
    kapt 'org.mapstruct:mapstruct-processor:1.3.1.Final'
    api "com.github.pozo:mapstruct-kotlin:1.3.1.1"
    kapt "com.github.pozo:mapstruct-kotlin-processor:1.3.1.1"

**Comment by Pozo** [comment]
@arberg Thank you for the information, I'll look into it.

**Comment by Pozo** [comment]
@arberg Now it's available from the central repository, the version number is [1.3.1.2](https://search.maven.org/artifact/com.github.pozo/mapstruct-kotlin-processor/1.3.1.2/jar)
